config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'family', to: 'pages#family'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100}
  validates :description, presence: true, length: { minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy] #perform this method before running code for the methods listed

  def show
  end

  def index
    @articles = Article.all 
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create 
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was created successfully." #can choose any name to give flash message but common symbols are :notice or :alert. Alert is usually for when something goes wrong.
      redirect_to @article #redirect using the show method (@article gives article id)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private #Anything below is a private method available only to this controller

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params 
    params.require(:article).permit(:title, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end

  def saly
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved:</h2>
  <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
  </ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Cancel and return to articles listing', articles_path %>

app/views/articles/index.html.erb
<h1>Articles Listing Page</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article)%></td>
        <td><%= button_to 'Delete', article_path(article), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
  
</table>

<p>
  <%= link_to 'Create new article', new_article_path %>
</p>

<p>
  <%= link_to 'Return to Home Page', root_path %>
</p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>

<%= link_to 'Return to articles listing', articles_path %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Return to articles listing', articles_path %>

<p>
  <%= button_to 'Delete', article_path(@article), method: :delete %>
</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about screen</h1>

<p>
  <%= link_to 'Return to Home Page', root_path %>
</p>

app/views/pages/family.html.erb
<h1>My Beautiful Family</h1>
<h2>Hello My Darling</h2>
<p>You are a beautiful angel and the most perfect woman I could ever hope for.</p>
<%= image_tag "chris_and_saly.jpg", height: 300 %>
<h2>My darling and my son</h2>
<p>I love you both more than I could ever let you know. I adore you both. I love you and miss you every second. Everything I do is for both of you.</p>
<%= image_tag "saly_and_floop.jpg", height: 500 %>
<h2>Our Little Floop</h2>
<p>The most precious beautiful angel on earth</p>

<table>
  <tr>
    <td>
      <%= image_tag "floop_sitting.jpg", height: 300%>
      <figcaption>Floopy Sitting</figcaption>
    </td>
    <td>
      <%= image_tag "floop_bathing.jpg", height: 300%>
      <figcaption>Floop Bathing</figcaption>
    </td>
    <td>
      <%= image_tag "floop_waking_up.jpg", height: 300%>
      <figcaption>Floop Waking Up</figcaption>
    </td>
  </tr>
    <td>
      <%= image_tag "floop_on_the_stairs.jpg", height: 300%>
      <figcaption>Floop On The Stairs</figcaption>
    </td>
    <td>
      <%= image_tag "floop_in_a_hat_1.jpg", height: 300%>
      <figcaption>Floop In A Hat!</figcaption>
    </td>
    <td>
      <%= image_tag "floop_in_a_hat_2.jpg", height: 300%>
      <figcaption>Floop In Another Hat!</figcaption>
    </td>
</table>

<p>
  <%= link_to 'Return to Home Page', root_path %>
</p>

app/views/pages/home.html.erb
<h1>This is the home screen</h1>

<%= link_to 'Articles Listing', articles_path %> |
<%= link_to 'Family', family_path %> |
<%= link_to 'About', about_path %> |